name: EKS Cluster Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Create EKS Cluster
        run: |
          eksctl create cluster --name markrtting-dev-markettingeks --region us-west-2

      - name: Deploy voting-app to EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'create') }}
        run: |
          cd kubernetes/voting-app
          terraform init
          terraform apply -auto-approve

      - name: Deploy sock-shop to EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'create') }}
        run: |
          cd kubernetes/micro-service
          terraform init
          terraform apply -auto-approve

      - name: Deploy ingress rule to EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'create') }}
        run: |
          cd kubernetes/ingress-rule
          terraform init
          terraform apply -auto-approve

      - name: Create nginx-controller & route53
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'create') }}
        run: |
          cd kubernetes/nginx-controller
          terraform init
          terraform apply -auto-approve

      - name: Destroy prometheus
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy') }}
        run: |
          cd kubernetes/prometheus-helm
          terraform destroy -auto-approve

      - name: Destroy voting-app in EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy') }}
        run: |
          cd kubernetes/voting-app
          terraform destroy -auto-approve

      - name: Destroy sock-shop in EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy') }}
        run: |
          cd kubernetes/micro-service
          terraform destroy -auto-approve

      - name: Destroy ingress rule in EKS
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy') }}
        run: |
          cd kubernetes/ingress-rule
          terraform destroy -auto-approve

      - name: Destroy nginx-conroller
        if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'destroy') }}
        run: |
          cd kubernetes/nginx-controller
          terraform destroy -auto-approve
